AWSTemplateFormatVersion: '2010-09-09'
Description: Simple test stack for validation permissions

Resources:
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: test-krishi-validation-680125699864

Outputs:
  BucketName:
    Description: Test bucket name
    Value: !Ref TestBucket